[package]
name = "lightmark"
version = "0.5.4"
description = "轻量、离线的 Markdown 阅读与编辑器"
authors = ["Willie Wei"]
license = "MIT"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
anydoc = "=0.1.8"
base64 = "0.22"
log = "0.4"
mime_guess = "2"
percent-encoding = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
tauri-plugin-single-instance = "2"
